corpus:
  word2vec: data/word2vec_corpus.pkl.gz
  fun2vec: data/fun2vec_corpus.pkl.gz
  fun2vec_clustered: data/fun2vec_clustered_corpus.pkl.gz
model:
  word2vec: data/word2vec.model.gz
  fun2vec: data/fun2vec.model.gz
topic_model: data/topic_model.model.gz
mecab:
    dicdir:  /usr/local/lib/mecab/dic/mecab-ipadic-neologd
    userdics:
      - data/dictionary/original_dic.dic
word:
  stop_words: data/dictionary/stop_words.txt
