word2vec:
    corpus: data/word2vec_corpus.pkl
    model: data/word2vec.model
fun2vec:
    corpus: data/fun2vec_corpus.pkl
    model: data/fun2vec.model
    dictionary: data/fun2vec_dictionary.pkl
stop_words: data/stop_words.csv
