word:
  stop_words: data/dictionary/stop_words.txt
mecab:
  dicdir:  /usr/local/lib/mecab/dic/mecab-ipadic-neologd
  userdics:
    - data/dictionary/original_dic.dic
corpus:
  word2vec: data/word2vec_corpus.pkl.gz
  fun2vec: data/fun2vec_corpus.pkl.gz
  fun2vec_clustered: data/fun2vec_clustered_corpus.pkl.gz
cluster:
  kmeans: data/kmeans.pkl
  minibatch_kmeans: data/minibatch_kmeans.pkl
  agglomerate: data/agglomerate.pkl
  dbscan: data/dbscan.pkl
model:
  word2vec: data/word2vec.model.gz
  fun2vec: data/fun2vec.model.gz
  fun2vec_clustered: data/fun2vec_clustered.model.gz
