version: 1
formatters:
  consoleFormatter:
    format: '[%(asctime)s][%(levelname)s][%(name)s #%(funcName)s:%(lineno)d] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  appHandler:
    class: logging.StreamHandler
    formatter: consoleFormatter
    level: INFO

root:
  level: INFO
  handlers: [appHandler]

disable_existing_loggers: no
